// <auto-generated />
namespace Thermo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class first2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first2));
        
        string IMigrationMetadata.Id
        {
            get { return "201404041009530_first2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
