// <auto-generated />
namespace Thermo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required));
        
        string IMigrationMetadata.Id
        {
            get { return "201404070855150_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
