// <auto-generated />
namespace Thermo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class profil : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(profil));
        
        string IMigrationMetadata.Id
        {
            get { return "201404300913039_profil"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
