// <auto-generated />
namespace Thermo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user));
        
        string IMigrationMetadata.Id
        {
            get { return "201404050923530_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
