//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ressources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer est une action irréversible.
        /// </summary>
        public static string actionirr {
            get {
                return ResourceManager.GetString("actionirr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail additionnel.
        /// </summary>
        public static string additionalmail {
            get {
                return ResourceManager.GetString("additionalmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tél additionnel.
        /// </summary>
        public static string additionalphone {
            get {
                return ResourceManager.GetString("additionalphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des alarmes.
        /// </summary>
        public static string alarmlist {
            get {
                return ResourceManager.GetString("alarmlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moyenne.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à la liste.
        /// </summary>
        public static string BacktoList {
            get {
                return ResourceManager.GetString("BacktoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les éléments de base.
        /// </summary>
        public static string baseelement {
            get {
                return ResourceManager.GetString("baseelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string becareful {
            get {
                return ResourceManager.GetString("becareful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir l&apos;utilisateur.
        /// </summary>
        public static string chooseuser {
            get {
                return ResourceManager.GetString("chooseuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermée.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réduire.
        /// </summary>
        public static string Collapseall {
            get {
                return ResourceManager.GetString("Collapseall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer mot de passe.
        /// </summary>
        public static string confirmpassword {
            get {
                return ResourceManager.GetString("confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau compte.
        /// </summary>
        public static string Createanewaccount {
            get {
                return ResourceManager.GetString("Createanewaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau équipement.
        /// </summary>
        public static string createequipment {
            get {
                return ResourceManager.GetString("createequipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string Createnew {
            get {
                return ResourceManager.GetString("Createnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une nouvelle zone.
        /// </summary>
        public static string createnewzone {
            get {
                return ResourceManager.GetString("createnewzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de création.
        /// </summary>
        public static string Datecreation {
            get {
                return ResourceManager.GetString("Datecreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer cet équipement?.
        /// </summary>
        public static string deleteequipment {
            get {
                return ResourceManager.GetString("deleteequipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer cet  utilisateur?.
        /// </summary>
        public static string deleteuser {
            get {
                return ResourceManager.GetString("deleteuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail de la chambre froide.
        /// </summary>
        public static string detailchambre {
            get {
                return ResourceManager.GetString("detailchambre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail pour.
        /// </summary>
        public static string detailsfor {
            get {
                return ResourceManager.GetString("detailsfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer éuipement.
        /// </summary>
        public static string Editequipement {
            get {
                return ResourceManager.GetString("Editequipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer lieu.
        /// </summary>
        public static string editlocation {
            get {
                return ResourceManager.GetString("editlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez éditer vos informations.
        /// </summary>
        public static string edituserinfo {
            get {
                return ResourceManager.GetString("edituserinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer zone.
        /// </summary>
        public static string editzone {
            get {
                return ResourceManager.GetString("editzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date fin.
        /// </summary>
        public static string Enddate {
            get {
                return ResourceManager.GetString("Enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer la fréquence de rappel.
        /// </summary>
        public static string enterfrequency {
            get {
                return ResourceManager.GetString("enterfrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le nom de l&apos;équipement.
        /// </summary>
        public static string enternameequip {
            get {
                return ResourceManager.GetString("enternameequip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le nom.
        /// </summary>
        public static string enternamelocation {
            get {
                return ResourceManager.GetString("enternamelocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre numéro de tél de nuit.
        /// </summary>
        public static string enternightnumber {
            get {
                return ResourceManager.GetString("enternightnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre numéro de tél.
        /// </summary>
        public static string enterphone {
            get {
                return ResourceManager.GetString("enterphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer l&apos;Id de l&apos;équipement.
        /// </summary>
        public static string enterserialnum {
            get {
                return ResourceManager.GetString("enterserialnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre prénom.
        /// </summary>
        public static string enteryourlastname {
            get {
                return ResourceManager.GetString("enteryourlastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer un nom d&apos;un lieu. Il sera utilisé plus tard pour ajouter un equipements..
        /// </summary>
        public static string enteryourlocation {
            get {
                return ResourceManager.GetString("enteryourlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre mail.
        /// </summary>
        public static string enteryourmail {
            get {
                return ResourceManager.GetString("enteryourmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre nom.
        /// </summary>
        public static string enteryourname {
            get {
                return ResourceManager.GetString("enteryourname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;équipement.
        /// </summary>
        public static string Equipement {
            get {
                return ResourceManager.GetString("Equipement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;équipement.
        /// </summary>
        public static string Equipementname {
            get {
                return ResourceManager.GetString("Equipementname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernières mesures des équipements.
        /// </summary>
        public static string EquipementsLastsmeasures {
            get {
                return ResourceManager.GetString("EquipementsLastsmeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des équipements.
        /// </summary>
        public static string Equipementslist {
            get {
                return ResourceManager.GetString("Equipementslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;évènement.
        /// </summary>
        public static string EvenementType {
            get {
                return ResourceManager.GetString("EvenementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evènements.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des évènements.
        /// </summary>
        public static string eventslist {
            get {
                return ResourceManager.GetString("eventslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etendre.
        /// </summary>
        public static string Expandall {
            get {
                return ResourceManager.GetString("Expandall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Première alarme.
        /// </summary>
        public static string Firstalarme {
            get {
                return ResourceManager.GetString("Firstalarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pour.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fréquence de rappel.
        /// </summary>
        public static string frequency {
            get {
                return ResourceManager.GetString("frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphique.
        /// </summary>
        public static string Graphs {
            get {
                return ResourceManager.GetString("Graphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarme haute.
        /// </summary>
        public static string HighAlarm {
            get {
                return ResourceManager.GetString("HighAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarme Haute.
        /// </summary>
        public static string Hightalarme {
            get {
                return ResourceManager.GetString("Hightalarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consignes.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justifier.
        /// </summary>
        public static string Justify {
            get {
                return ResourceManager.GetString("Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière date de mesure.
        /// </summary>
        public static string LastdateofMeasurement {
            get {
                return ResourceManager.GetString("LastdateofMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière mesure.
        /// </summary>
        public static string LastMesure {
            get {
                return ResourceManager.GetString("LastMesure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des lieux.
        /// </summary>
        public static string ListofLocations {
            get {
                return ResourceManager.GetString("ListofLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieu.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail de lieu.
        /// </summary>
        public static string locationdetail {
            get {
                return ResourceManager.GetString("locationdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de lieu.
        /// </summary>
        public static string locationname {
            get {
                return ResourceManager.GetString("locationname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieux.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarme faible.
        /// </summary>
        public static string LowAlarm {
            get {
                return ResourceManager.GetString("LowAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarme basse.
        /// </summary>
        public static string Lowalarme {
            get {
                return ResourceManager.GetString("Lowalarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail de weekend.
        /// </summary>
        public static string Mailweekend {
            get {
                return ResourceManager.GetString("Mailweekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum enregistré.
        /// </summary>
        public static string Maximumregistred {
            get {
                return ResourceManager.GetString("Maximumregistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesures.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum enregistré.
        /// </summary>
        public static string Minimumregistred {
            get {
                return ResourceManager.GetString("Minimumregistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus d&apos;info.
        /// </summary>
        public static string moreinfo {
            get {
                return ResourceManager.GetString("moreinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau lieu.
        /// </summary>
        public static string newlocation {
            get {
                return ResourceManager.GetString("newlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un nouveau zone.
        /// </summary>
        public static string newzone {
            get {
                return ResourceManager.GetString("newzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de tél de nuit.
        /// </summary>
        public static string NightNumber {
            get {
                return ResourceManager.GetString("NightNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si vous voulez vraiment supprimer cet objet cliker sur le bouton supprimer.
        /// </summary>
        public static string option1 {
            get {
                return ResourceManager.GetString("option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur Retour à la liste pour annuler.
        /// </summary>
        public static string option2 {
            get {
                return ResourceManager.GetString("option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aperçu général.
        /// </summary>
        public static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tél personnel.
        /// </summary>
        public static string PersonalPhone {
            get {
                return ResourceManager.GetString("PersonalPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouméro de tél.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez confirmer votre mot de passe.
        /// </summary>
        public static string Pleaseconfirmyourpassword {
            get {
                return ResourceManager.GetString("Pleaseconfirmyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre nom d&apos;utilisateur.
        /// </summary>
        public static string Pleaseenterausername {
            get {
                return ResourceManager.GetString("Pleaseenterausername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir vos données.
        /// </summary>
        public static string pleaseenteryourinformations {
            get {
                return ResourceManager.GetString("pleaseenteryourinformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre mot de passe, il doit contenir 6 caractères.
        /// </summary>
        public static string Pleaseenteryourpassword {
            get {
                return ResourceManager.GetString("Pleaseenteryourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer la temporisation de déclenchement de l&apos;alarme.
        /// </summary>
        public static string popupfirst {
            get {
                return ResourceManager.GetString("popupfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrez une valeur de l&apos;alarme haute. C&apos;est la valeur pour le déclenchement de l&apos;alarme pour cet équipement.
        /// </summary>
        public static string popuphight {
            get {
                return ResourceManager.GetString("popuphight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrez une valeur de l&apos;alarme faible. C&apos;est la valeur pour le déclenchement de l&apos;alarme pour cet équipement.
        /// </summary>
        public static string popuplow {
            get {
                return ResourceManager.GetString("popuplow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des sondes.
        /// </summary>
        public static string problist {
            get {
                return ResourceManager.GetString("problist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        public static string Responsability {
            get {
                return ResourceManager.GetString("Responsability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsables.
        /// </summary>
        public static string Responsables {
            get {
                return ResourceManager.GetString("Responsables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rôle.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner l&apos;utilisateur.
        /// </summary>
        public static string SelectUsers {
            get {
                return ResourceManager.GetString("SelectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capteur.
        /// </summary>
        public static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sondes.
        /// </summary>
        public static string Seonsors {
            get {
                return ResourceManager.GetString("Seonsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de série.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sonde Id.
        /// </summary>
        public static string SondeId {
            get {
                return ResourceManager.GetString("SondeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail de sonde.
        /// </summary>
        public static string sondesdetail {
            get {
                return ResourceManager.GetString("sondesdetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date début.
        /// </summary>
        public static string Startdate {
            get {
                return ResourceManager.GetString("Startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiques.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer ce lieu?.
        /// </summary>
        public static string surewanttodelete {
            get {
                return ResourceManager.GetString("surewanttodelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etes-vous sûr de vouloir supprimer cet zone?.
        /// </summary>
        public static string surewanttodeletezone {
            get {
                return ResourceManager.GetString("surewanttodeletezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations de l&apos;utilisateur.
        /// </summary>
        public static string userinfo {
            get {
                return ResourceManager.GetString("userinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des utilisateurs.
        /// </summary>
        public static string userslist {
            get {
                return ResourceManager.GetString("userslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir profile.
        /// </summary>
        public static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voici ce que vous pouvez faire.
        /// </summary>
        public static string wahtcan {
            get {
                return ResourceManager.GetString("wahtcan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de tél de weekend.
        /// </summary>
        public static string weekendnumber {
            get {
                return ResourceManager.GetString("weekendnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre mail additionnel.
        /// </summary>
        public static string youradditional {
            get {
                return ResourceManager.GetString("youradditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre mail de weekend.
        /// </summary>
        public static string yourmailwkd {
            get {
                return ResourceManager.GetString("yourmailwkd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer votre numéro de weekend.
        /// </summary>
        public static string yourweekendnumber {
            get {
                return ResourceManager.GetString("yourweekendnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail du zone.
        /// </summary>
        public static string zonedetail {
            get {
                return ResourceManager.GetString("zonedetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des zones.
        /// </summary>
        public static string zonelist {
            get {
                return ResourceManager.GetString("zonelist", resourceCulture);
            }
        }
    }
}
